services:
  nginx-debug:
    image: openresty/openresty:1.29.2.3-alpine-fat
    platform: linux/arm64
    container_name: nginx-proxy-debug
    ports:
      - "${DEBUG_PROXY_PORT:-8888}:8888"
    volumes:
      - ./nginx.debug.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./logs:/var/log/nginx
    networks:
      - development-network

networks:
  development-network:
    external: true