services:
  open-webui-host:
    image: ghcr.io/open-webui/open-webui:latest
    platform: linux/arm64
    container_name: open-webui-host
    hostname: web-ui-server
    network_mode: "host"
    volumes:
      - open-webui-host:/app/backend/data
    environment:
      - OPENAI_API_BASE_URL=http://localhost:8000/v1
      - OPENAI_API_KEY=${INFERENCE_API_KEY:-dummy-key}
      - WEBUI_AUTH=${WEBUI_AUTH:-false}
    restart: no

volumes:
  open-webui-host:
