version: '3.8'

services:
  # Ollama service configuration
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      #- ollama:/root/.ollama
      - ./downloaded_models:/root/.ollama
    environment:
      # see: https://aider.chat/docs/llms/ollama.html
      - OLLAMA_CONTEXT_LENGTH=128000
      - OLLAMA_API_KEY=Irrelevant
      - OLLAMA_KEEP_ALIVE=3h
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: no

  # Open-WebUI service configuration
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    ports:
      - "11435:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
      - WEBUI_AUTH=false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: no

volumes:
  # ollama:
  open-webui:
