services:
  nemotron-vllm:
    image: mutazai/nemotron3-30b-nvfp4-vllm-cuda13
    container_name: nemotron-vllm
    hostname: nemotron-vllm
    ports:
      - "8000:8000"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - VLLM_WORKER_MULTIPROC_METHOD=spawn
    networks:
      - development-network
    # restart: unless-stopped

networks:
  development-network:
    external: true